---
name: publish artifacts
# yamllint disable-line rule:truthy
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on default branch
#      - devel
      # Push events to branches matching refs/heads/release-v*
#      - 'release-v*'
      - zhujq
permissions:
  contents: read

jobs:
  push:
    name: Publish artifacts
    runs-on: ubuntu-latest
    if: github.repository == 'acechef/ceph-csi'
    steps:
      - uses: actions/checkout@v4

      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Set build environment variables
        run: |
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "GITHUB_USER=bot" >> $GITHUB_ENV
          echo "GITHUB_EMAIL=a@bot.com" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=1234" >> $GITHUB_ENV

      - name: publish artifacts
        # podman cannot pull images with both tag and digest
        # https://github.com/containers/buildah/issues/1407
        # use docker to build images
        run: CONTAINER_CMD=docker ./deploy.sh
